### ISSUE TITLE
Shorten all paths to under 190 characters

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetDocs#403]
- FInd all all `MD` and `.png` files with path length after `https://github.com/dotnet/AspNetDocs` > 180.
- Rename asset to be  under 180.

Examples;
*  https://github.com/dotnet/AspNetDocs/blob/live/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/migrations-and-deployment-with-the-entity-framework-in-an-asp-net-mvc-application/_static/server-explorer-stop-app-service.png
* https://github.com/dotnet/AspNetDocs/blob/live/aspnet/mvc/overview/older-versions/using-the-html5-and-jquery-ui-datepicker-popup-calendar-with-aspnet-mvc/using-the-html5-and-jquery-ui-datepicker-popup-calendar-with-aspnet-mvc-part-1/_static/image1.png

**Comment by wadepickett** [comment]
Localization team fixed on localization process side.  We decided the fix should be there since the shortened path issue would restrict every repo published across docs.microsoft.com and require many to rename/touch too many directories/file names for content and dependencies including the code samples.
