### ISSUE TITLE
Fix links for 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetDocs#491]
https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions/getting-started-with-ef-5-using-mvc-4/implementing-the-repository-and-unit-of-work-patterns-in-an-asp-net-mvc-application#the-repository-and-unit-of-work-patterns.

 two broken links with 404   errors on    Implementing the Repository and Unit of Work Patterns in an ASP.NET MVC   Application (9 of 10) documentation.       1. Link of "Download Completed Project"      2. Link of "Using Repository and Unit of Work patterns with Entity   Framework 4.0" are missing.

Expanding this to fix sample links in the entire series: (wadepickett)

- Creating an Entity Framework Data Model
- Implementing Basic CRUD Functionality
- Sorting, Filtering, and Paging
- Creating a More Complex Data Model
- Reading Related Data
- Updating Related Data
- Handling Concurrency
- Implementing Inheritance
- Implementing the Repository and Unit of Work Patterns
- Advanced Entity Framework Scenarios
- Building the Chapter Downloads

--

**Comment by Rick-Anderson** [comment]
@wadepickett  can you get this fixed this week?

**Comment by wadepickett** [comment]
@Rick-Anderson,  It looks like the Contoso Employees sample no longer exists.   Samples were archived in 2019 to a public repo for samples for anything that had reasonable traffic.  This one does not appear there as far as I can see.   Looking over past PR's related to that transfer, links were being removed if they previously pointed to the low traffic samples that didn't make the cut to that archive and no longer exists.

Unless you suggest otherwise, I will go ahead remove the links throughout this series which are located at the top of each tutorial unit.

**Comment by wadepickett** [comment]
Remaining link I missed has been taken care of in PR #495.
