### ISSUE TITLE
Unclear green line highlighting in code example on HTTP example

### ISSUE THREAD

**Issue by chingucoding** [dotnet/AspNetDocs#497]
# Issue description
The last code example on [this page](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client#sending-a-delete-request-to-delete-a-resource) has a a green line on the second line:
![Image showing code example where the second lie is highlighted using green ](https://user-images.githubusercontent.com/16122379/108603987-7ab1b300-73ab-11eb-873e-12a12f330296.png)

**Comment by Rick-Anderson** [comment]
It's not specifying highlighting
`[!code-csharp[Main](calling-a-web-api-from-a-net-client/sample/client/Program.cs?name=snippet5)]`

**Comment by chingucoding** [comment]
So the green line is here to stay then? What is it trying to convey to the reader?

It's visible in Edge Dev, Chrome and Firefox, so this has to be an issue with the page, not the browsers.

**Comment by Rick-Anderson** [comment]
Why aren't you learning ASP.NET Core?

**Comment by michael-hawker** [comment]
@Rick-Anderson it doesn't matter what technology someone is using when they file an issue in your repo. This is a legitimate issue, it should be re-opened and investigated. If you think your content is correct, you should open a ticket against the doc team to investigate their doc generation code. I also see the same issue, even on my mobile device browser and in Edge 88.0.705.74:

![image](https://user-images.githubusercontent.com/24302614/109195875-e56a4200-774f-11eb-8266-0083ebe5f702.png)

**Comment by michael-hawker** [comment]
@Rick-Anderson looking at other comments in the repo here, I think you're trying to instead imply that why is someone looking at ASP 4.x docs instead of ASP Core docs. If these are old/out-dated docs then, that should be stated in the repo and these pages should point to the new .NET Core equivalents to help folks understand they're not looking at the right ones. Most folks are probably landing on these from Bing/Google searches which wouldn't provide context that they're for old .NET Framework versions and not the latest implementation.

I'm also not sure where you found your snippet code, as I clearly see this with the highlight in the main branch:

```
[!code-csharp[Main](calling-a-web-api-from-a-net-client/sample/client/Program.cs?name=snippet5&highlight=2)]
```

Submitting a PR to fix.

**Comment by chingucoding** [comment]
@Rick-Anderson I wasn't learning an old ASP.NET Core, I searched for "c# httpclient" and this was the first non API doc that showed up, so I visited the page since this would give a good example of how to use the class, something normal API documentation usually does not do.

**Comment by Rick-Anderson** [comment]
@michael-hawker  no I'm not implying anything about the technology. I'm was just curious and it turns out I was right.

I was actually looking into it and apparently looked at the wrong snippet.
